server:
  port: 14000

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        - name: CircuitBreaker
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback

      routes:
        - id: userServer
          uri: lb://user-server
          predicates:
            - Path=/UserController/*/**

        - id: foodServer
          uri: lb://food-server
          predicates:
            - Path=/FoodController/*/**

        - id: businessServer
          uri: lb://business-server
          predicates:
            - Path=/BusinessController/*/**
          filters:
            - name: CircuitBreaker
              args:
                name: businessCircuitBreaker
                fallbackUri: forward:/fallback/business

        - id: cartServer
          uri: lb://cart-server
          predicates:
            - Path=/CartController/*/**

        - id: deliveryaddressServer
          uri: lb://deliveryaddress-server
          predicates:
            - Path=/DeliveryaddressController/*/**

        - id: ordersServer
          uri: lb://orders-server
          predicates:
            - Path=/OrdersController/*/**

resilience4j:
  circuitbreaker:
    instances:
      fallbackcmd:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5000
        failureRateThreshold: 50




eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer13000:13000/eureka,http://eurekaServer13001:13001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
