server:
  port: 15000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/rieraa/elm-scc.git

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456


eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer13000:13000/eureka/,http://eurekaServer13001:13001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    busrefresh:
      enabled: true
    health:
      show-details: always
