server:
  port: 10100
logging:
  level:
    org.springframework:
    debug com.Iynew.mapper: debug
spring:
  application:
    name: user-server
  datasource:
    username: root
    password: 256889559yY
    url: jdbc:mysql://sh-cynosdbmysql-grp-lr3zkq1e.sql.tencentcdb.com:23946/elmSpringCloud?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations:
  classpath:mapper/*.xml type-aliases-package: com.Iynew.po