server:
  port: 10100
logging:
  level:
    org.springframework: debug
    debug com.Iynew.mapper: debug
spring:
  application:
    name: user-server
  datasource:
    username: root
    password: "2568898559yY"
    url: jdbc:mysql://sh-cynosdbmysql-grp-lr3zkq1e.sql.tencentcdb.com:23946/elmSpringCloud?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  classpath:mapper/*.xml type-aliases-package: com.Iynew.po

#eureka配置
eureka:
  client:
    service-url:
  #将自己注册给Eureka Server集群
      defaultZone: http://eurekaServer13000:13000/eureka,http://eurekaServer13001:13001/eureka
  instance:
    prefer-ip-address: true #使用ip地址向Eureka注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #自定义微服务实例ID
